Repository submariner-io/submariner-website, pull requests merged in 2020-09, with the labels that each got.

#253 v0.6.0 release notes
  src/content/releases/_index.en.md
Labels: documentation

#243 Document our monitoring setup
  src/content/contributing/_index.en.md
  src/content/monitoring/_index.en.md
  src/content/reading_material/_index.en.md
  src/content/releases/_index.en.md
  src/content/roadmap/_index.en.md
  src/content/troubleshooting/_index.en.md
Labels: documentation

#271 Update SubM roadmap docs, describe planning process
  src/content/roadmap/_index.en.md
Labels: cncf, documentation

#280 Add docs about pronouncing "Submariner"
  src/content/contributing/website/style_guide.md
Labels: cncf, documentation

#186 Helm details
  src/content/deployment/helm/_index.en.md
Labels: documentation

#282 Correct "on-premise" to "on-premises"
  src/content/_index.en.md
  src/content/architecture/_index.en.md
  src/content/architecture/broker/_index.en.md
  src/content/quickstart/vsphere_aws/_index.md
Labels: cncf, documentation

#283 Reorder left-side nav sections to be ABC order
  src/content/contributing/code-review/_index.en.md
  src/content/contributing/community-membership/_index.en.md
  src/content/contributing/lighthouse/_index.en.md
  src/content/contributing/release-process/_index.en.md
  src/content/contributing/shipyard/_index.en.md
  src/content/contributing/website/_index.en.md
  src/content/quickstart/kind/_index.md
  src/content/quickstart/openshift/_index.md
  src/content/quickstart/rancher/_index.md
  src/content/quickstart/vsphere_aws/_index.md
Labels: cncf, documentation

#286 Fix origin story of Submariner name
  src/content/contributing/website/style_guide.md
Labels: cncf, documentation

#285 Refactor Building and Testing docs
  src/content/contributing/building_testing/_index.en.md
Labels: automation, cncf, documentation

#289 Add links to recordings of Submariner SIG demos
  src/content/reading_material/_index.en.md
Labels: cncf, documentation
