Repository submariner-io/submariner-website, pull requests merged in 2020-08, with the labels that each got.

#221 Enable ul-style MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/community-membership/_index.en.md
  src/content/quickstart/_index.en.md
  src/content/releases/_index.en.md
Labels: automation, cncf, documentation

#222 Enable blanks-around-fences MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/shipyard/advanced/_index.en.md
  src/content/contributing/website/_index.en.md
  src/content/deployment/_index.en.md
  src/content/quickstart/verify_with_discovery.md
  src/content/troubleshooting/_index.en.md
Labels: automation, cncf, documentation

#223 Enable no-space-in-code linting, fix errors
  .markdownlint.yml
  src/content/deployment/subctl.en.md
  src/content/troubleshooting/_index.en.md
Labels: automation, cncf, documentation

#225 Enable no-inline-html MD linting, fix errors
  .markdownlint.yml
  src/content/_index.en.md
Labels: automation, cncf, documentation

#224 Enable blanks-around-lists MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/shipyard/_index.en.md
  src/content/contributing/shipyard/advanced/_index.en.md
  src/content/deployment/subctl.en.md
  src/content/quickstart/_index.en.md
  src/content/reading_material/_index.en.md
  src/content/roadmap/_index.en.md
Labels: automation, cncf, documentation

#227 Enable ul-indent MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/community-membership/_index.en.md
  src/content/deployment/subctl.en.md
  src/content/releases/_index.en.md
Labels: automation, cncf, documentation

#228 Enable ol-prefix MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/website/_index.en.md
Labels: automation, cncf, documentation

#229 Enable blanks-around-headers MD linting, fix errs
  .markdownlint.yml
  src/content/_index.en.md
  src/content/architecture/service-discovery/_index.en.md
  src/content/quickstart/_index.en.md
  src/content/quickstart/kind/_index.md
  src/content/quickstart/verify_with_discovery.md
  src/content/releases/_index.en.md
  src/content/roadmap/_index.en.md
  src/content/troubleshooting/_index.en.md
Labels: automation, cncf, documentation

#233 Enable fenced-code-language MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/building_testing/_index.en.md
  src/content/contributing/lighthouse/_index.en.md
  src/content/contributing/shipyard/_index.en.md
  src/content/contributing/shipyard/advanced/_index.en.md
  src/content/contributing/shipyard/first_time/_index.en.md
  src/content/troubleshooting/_index.en.md
Labels: automation, cncf, documentation

#232 Enable single-h1 MD linting, fix errors
  .markdownlint.yml
  src/content/_index.en.md
Labels: automation, cncf, documentation

#230 Enable no-duplicate-header MD linting, fix errors
  .markdownlint.yml
  src/content/architecture/service-discovery/_index.en.md
  src/content/contributing/community-membership/_index.en.md
Labels: automation, cncf, documentation

#235 Enable no-bare-urls MD linting, fix errors
  .markdownlint.yml
  src/content/contributing/release-process/_index.en.md
  src/content/quickstart/openshift/setup_openshift.md
  src/content/quickstart/vsphere_aws/_index.md
  src/content/releases/_index.en.md
  src/content/roadmap/_index.en.md
Labels: automation, cncf, documentation

#234 Use HTML to increase font size vs header levels
  .markdownlint.yml
  src/content/_index.en.md
Labels: automation, cncf, documentation

#231 Enable no-trailing-punctuation linting, fix errs
  .markdownlint.yml
  src/content/_index.en.md
  src/content/contributing/_index.en.md
Labels: automation, cncf, documentation

#237 Enable single-trailing-newline linting, fix errs
  .markdownlint.yml
  src/content/quickstart/rancher/create_clusters.md
  src/content/quickstart/rancher/prerequisites.md
Labels: automation, cncf, documentation

#238 Enable header-start-left and ul-start-left MD lint
  .markdownlint.yml
Labels: automation, cncf, documentation

#240 Use subdir for subctl docs
  src/content/releases/_index.en.md
Labels: automation, cncf, documentation

#244 Enable line-length MD linting, fix errors
  .markdownlint.yml
  src/content/_index.en.md
  src/content/architecture/_index.en.md
  src/content/architecture/globalnet/_index.en.md
  src/content/contributing/_index.en.md
  src/content/contributing/building_testing/_index.en.md
  src/content/contributing/lighthouse/_index.en.md
  src/content/contributing/shipyard/_index.en.md
  src/content/contributing/shipyard/advanced/_index.en.md
  src/content/contributing/shipyard/first_time/_index.en.md
  src/content/contributing/website/_index.en.md
  src/content/deployment/_index.en.md
  src/content/deployment/subctl/_index.en.md
  src/content/quickstart/_index.en.md
  src/content/quickstart/kind/_index.md
  src/content/quickstart/rancher/create_clusters.md
  src/content/quickstart/rancher/prerequisites.md
  src/content/quickstart/vsphere_aws/_index.md
  src/content/reading_material/_index.en.md
  src/content/releases/_index.en.md
  src/content/roadmap/_index.en.md
  src/content/troubleshooting/_index.en.md
Labels: automation, cncf, documentation

#245 Fix GHA for periodic MD links check
  .github/workflows/md-links-periodic.yml
Labels: automation, cncf, documentation

#248 Update the --subm-debug to --enabled-pod-debugging
  src/content/deployment/subctl/_index.en.md
Labels: UX, subctl

#247 Raise Issue if broken link detected by periodic CI
  .github/ISSUE_TEMPLATE/broken-link.md
  .github/workflows/md-links-periodic.yml
Labels: automation, cncf, documentation

#254 Bump MD link check linter 0.6->1.*
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
Labels: automation, cncf, documentation

#256 Add YAML linting, fix errors
  .github/workflows/check_pr.yml
  .github/workflows/dco-check.yml
  .github/workflows/md-links-periodic.yml
  .github/workflows/md-links.yml
  .github/workflows/md-lint.yml
  .github/workflows/publish.yml
  .github/workflows/yaml-lint.yml
  .markdownlint.yml
  .yamllint.yml
Labels: automation, cncf

#260 Add SubM SD in OpenShift blog post link
  src/content/reading_material/_index.en.md
Labels: cncf, documentation

#255 Update troubleshooting guide for headless services
  src/content/troubleshooting/_index.en.md
Labels: documentation
