Repository submariner-io/submariner-website, pull requests merged in 2020-11, with the labels that each got.

#331 Clean up Code of Conduct, fix GH group
  src/content/contributing/code-of-conduct/_index.en.md
Labels: cncf, documentation

#333 Add Stephen Kitt to as Project Owner
  CODEOWNERS
Labels: automation

#334 Add link to DR with Submariner blog post
  src/content/reading_material/_index.en.md
Labels: documentation

#336 Clean up OpenShift on vSphere/AWS guide
  src/content/quickstart/openshift/run_prep_for_subm.md
  src/content/quickstart/vsphere_aws/_index.md
Labels: documentation

#335 Document the AWS instance type for the gateway node
  src/content/quickstart/openshift/_index.md
  src/content/quickstart/openshift/globalnet/_index.md
  src/content/quickstart/openshift/service_discovery/_index.md
Labels: documentation

#344 Clarify that Service Discovery is on by default
  src/content/architecture/_index.en.md
  src/content/architecture/globalnet/_index.en.md
  src/content/architecture/service-discovery/_index.en.md
Labels: documentation, ligthouse

#345 Update Service Discovery architecture page
  src/content/architecture/service-discovery/_index.en.md
Labels: documentation, ligthouse

#355 Clarify default broker/worker kind deploy config
  src/content/quickstart/kind/_index.md
Labels: documentation

#327 Add E2E focus flag to Building/Testing docs
  src/content/contributing/building_testing/_index.en.md
Labels: cncf, documentation

#369 Fix periodic broken link test issue reporting
  .github/ISSUE_TEMPLATE/broken-link.md
  .github/workflows/periodic.yml
Labels: automation
