Repository submariner-io/submariner-website, pull requests merged in 2020-12, with the labels that each got.

#387 Clarify CI part of website contribution process
  src/content/for_developers/dev_guide/website/_index.en.md
Labels: documentation

#394 Simplify subctl summary
  src/content/operations/deployment/subctl/_index.en.md
Labels: 0.8.0-testday, documentation

#396 Document the use of port 8080 in the OpenShift prep docs
  src/resources/shared/openshift/download_prep_for_subm.md
Labels: documentation

#391 Refactor GKE quickstart guide
  src/content/getting-started/quickstart/managed-kubernetes/gke/_index.md
Labels: 0.8.0-testday, documentation

#389 Fix all broken links
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  src/content/community/contributor-roles/_index.en.md
  src/content/community/roadmap/_index.en.md
  src/content/development/code-review/_index.en.md
Labels: documentation

#399 Doc need for owners to have * in all CODEOWNERS
  src/content/community/contributor-roles/_index.en.md
Labels: cncf, documentation

#407 Add "Update branch" guidance to code review guide
  src/content/development/code-review/_index.en.md
Labels: documentation

#404 Link to academic paper partly-about Submariner
  src/content/other-resources/_index.en.md
Labels: documentation
