Repository submariner-io/submariner-website, pull requests merged in 2020-10, with the labels that each got.

#290 Remove Lighthouse-specific contributing docs
  src/content/contributing/lighthouse/_index.en.md
Labels: cncf, documentation

#292 Capitalize Operator design pattern
  src/content/contributing/release-process/_index.en.md
  src/content/contributing/website/style_guide.md
  src/content/deployment/subctl/_index.en.md
  src/content/monitoring/_index.en.md
  src/content/reading_material/_index.en.md
  src/content/releases/_index.en.md
Labels: cncf, documentation

#293 Use "Globalnet", not "GlobalNet"
  src/content/quickstart/_index.en.md
  src/content/troubleshooting/_index.en.md
Labels: cncf, documentation

#291 Batch of Code Review docs refactoring
  src/content/contributing/code-review/_index.en.md
Labels: cncf, documentation

#301 Refactor Releases docs
  src/content/releases/_index.en.md
Labels: cncf, documentation

#319 Update usage instructions of prep_for_subm.sh
  src/content/quickstart/openshift/ready_clusters.md
  src/content/quickstart/vsphere_aws/_index.md
Labels: documentation

#321 Update release process for new Shipyard labels
  src/content/contributing/release-process/_index.en.md
Labels: automation, cncf, documentation

#323 Add conference presentation recording link
  src/content/reading_material/_index.en.md
Labels: documentation
