Repository submariner-io/submariner-website, pull requests merged in 2020-07, with the labels that each got.

#203 Fix minor typos in release notes
  src/content/releases/_index.en.md
Labels: documentation

#210 Remove demo videos from main page
  src/content/_index.en.md
Labels: cncf, documentation

#202 Update Lighthouse Docs
  src/content/deployment/with-discovery.md
  src/content/quickstart/kind/_index.md
  src/content/quickstart/verify_with_discovery.md
  src/content/troubleshooting/_index.en.md
Labels: QE, website

#207 Add subctl export
  src/content/deployment/subctl.en.md
Labels: website

#214 Add Markdown linter, ignore existing errors
  .github/workflows/md-lint.yml
  .markdownlint.yml
Labels: automation, cncf

#217 Enable no-trailing-spaces MD linting, fix errors
  .markdownlint.yml
  src/content/_index.en.md
  src/content/architecture/_index.en.md
  src/content/architecture/broker/_index.en.md
  src/content/architecture/gateway-engine/_index.en.md
  src/content/architecture/globalnet/_index.en.md
  src/content/architecture/route-agent/_index.en.md
  src/content/architecture/service-discovery/_index.en.md
  src/content/contributing/_index.en.md
  src/content/contributing/community-membership/_index.en.md
  src/content/contributing/release-process/_index.en.md
  src/content/deployment/_index.en.md
  src/content/deployment/subctl.en.md
  src/content/quickstart/_index.en.md
  src/content/quickstart/openshift/_index.md
  src/content/quickstart/openshift/create_clusters.md
  src/content/quickstart/openshift/ready_clusters.md
  src/content/quickstart/vsphere_aws/_index.md
  src/content/roadmap/_index.en.md
  src/content/troubleshooting/_index.en.md
Labels: automation, cncf, documentation

#218 Enable no-multiple-blanks MD linting, fix errors
  .markdownlint.yml
  src/content/_index.en.md
  src/content/contributing/code-review/_index.en.md
  src/content/contributing/release-process/_index.en.md
  src/content/contributing/shipyard/_index.en.md
  src/content/contributing/shipyard/first_time/_index.en.md
  src/content/contributing/website/_index.en.md
  src/content/deployment/_index.en.md
  src/content/deployment/subctl.en.md
  src/content/quickstart/_index.en.md
  src/content/quickstart/kind/_index.md
  src/content/quickstart/openshift/_index.md
  src/content/quickstart/openshift/create_clusters.md
  src/content/quickstart/openshift/globalnet/_index.md
  src/content/quickstart/openshift/setup_openshift.md
  src/content/quickstart/rancher/_index.md
  src/content/quickstart/vsphere_aws/_index.md
  src/content/releases/_index.en.md
Labels: automation, cncf, documentation

#219 Enable no-multiple-space-atx MD linting, fix errs
  .markdownlint.yml
  src/content/quickstart/kind/_index.md
  src/content/quickstart/verify_with_discovery.md
Labels: automation, cncf, documentation
