Repository submariner-io/submariner-website, pull requests merged in 2021-02, with the labels that each got.

#436 Fully move to devel branch
  .github/workflows/publish.yml
  scripts/make-all-versions
Labels: backport

#437 Update docs to reflect master->devel branch rename
  src/config.toml
  src/content/community/contributor-roles/_index.en.md
  src/content/development/building-testing/_index.en.md
  src/content/development/release-process/_index.en.md
  src/content/development/shipyard/_index.en.md
  src/content/development/shipyard/first-time/_index.en.md
  src/content/getting-started/architecture/globalnet/_index.en.md
  src/content/getting-started/quickstart/kind/_index.md
  src/content/operations/deployment/subctl/_index.en.md
  src/resources/shared/openshift/download_prep_for_subm.md
Labels: documentation

#435 Doc draft PRs for WIP, private forks for CI-bashing
  src/content/development/code-review/_index.en.md
Labels: documentation

#441 Change cluster name to b
  src/resources/shared/verify_with_discovery.md
Labels: backport

#439 v0.8.1 release notes
  src/content/community/releases/_index.en.md
Labels: backport

#446 Docs: prefix all metrics with submariner_
  src/content/operations/monitoring/_index.en.md
Labels: documentation

#451 Relicense docs to CC BY 4.0 per CNCF requirements
  LICENSE
Labels: cncf, documentation
