Repository submariner-io/submariner-website, pull requests merged in 2021-04, with the labels that each got.

#474 Add table of contents for empty sections
  src/content/community/_index.en.md
  src/content/development/_index.en.md
  src/content/getting-started/quickstart/_index.en.md
  src/content/getting-started/quickstart/managed-kubernetes/_index.en.md
  src/content/getting-started/quickstart/openshift/_index.md
  src/content/operations/_index.en.md
Labels: cncf, documentation

#475 Update Roadmap/Future Work overview docs
  src/content/community/roadmap/_index.en.md
Labels: cncf, documentation

#479 Fix style guide link
  src/content/development/_index.en.md
  src/content/development/website/style-guide/_index.en.md
Labels: bug, documentation

#471 Update flags description for subctl deploy-broker cmd
  src/content/operations/deployment/subctl/_index.en.md
Labels: documentation

#490 Remove target link instructions
  src/content/development/release-process/_index.en.md
Labels: documentation

#497 Disable the DCO GHA
  .github/workflows/linting.yml
Labels: cncf

#498 Change subctl validate to diagnose
  src/content/operations/deployment/subctl/_index.en.md
Labels: documentation
