Repository submariner-io/submariner-website, pull requests merged in 2021-05, with the labels that each got.

#457 Add release notes for 0.9.0
  src/content/community/releases/_index.en.md
Labels: documentation

#502 Add new materials to Other Resources section
  src/content/other-resources/_index.en.md
Labels: documentation

#512 Don't run certain GHA jobs on forks
  .github/workflows/periodic.yml
  .github/workflows/publish.yml
Labels: automation

#514 Refactor Getting Help docs
  src/content/community/getting-help/_index.en.md
Labels: cncf, documentation

#515 Document test policy for CII Best Practices
  src/content/development/code-review/_index.en.md
Labels: cncf, documentation

#517 Document that Submariner is a CNCF sandbox project
  src/content/_index.en.md
Labels: cncf, documentation, ready-to-test

#516 Add copyright notice to footer
  src/layouts/partials/menu-footer.html
Labels: cncf, documentation

#518 Document participates in security disclosures
  src/content/development/security/reporting/_index.en.md
Labels: cncf, documentation

#522 Add Linux Foundation trademark guidelines
  src/layouts/partials/menu-footer.html
Labels: cncf

#511 Remove permission warning for cloud prepare
  src/layouts/shortcodes/cloud-prepare/aws.md
Labels: backport

#523 Add CNCF logo and Sandbox statement to menu footer
  src/content/_index.en.md
  src/layouts/partials/menu-footer.html
Labels: cncf

#524 Document usage of `ready-to-test`
  src/content/development/code-review/_index.en.md
Labels: documentation

#519 Add KubeCon EU 2021 talk links
  src/content/other-resources/_index.en.md
Labels: documentation

#528 Reorder subctl installation section on OpenShift quickstarts
  src/content/getting-started/quickstart/openshift/aws/_index.md
  src/content/getting-started/quickstart/openshift/globalnet/_index.md
  src/content/getting-started/quickstart/openshift/vsphere-aws/_index.md
Labels: documentation

#527 Remove numbering of external resources, date-order
  src/content/other-resources/_index.en.md
Labels: cncf, documentation
