Repository submariner-io/submariner-website, pull requests merged in 2021-08, with the labels that each got.

#570 Don't run periodic PR dependency checks on forks
  .github/workflows/dependent-issues.yml
Labels: automation

#559 Document usage of kubecontexts in subctl benchmark
  src/content/operations/deployment/subctl/_index.en.md
Labels: subctl

#574 Fix typo in 0.10.1 release notes
  src/content/community/releases/_index.en.md
Labels: documentation
