Repository submariner-io/submariner-website, pull requests merged in 2021-06, with the labels that each got.

#485 NAT traversal info
  src/content/getting-started/_index.en.md
  src/content/operations/known-issues/_index.en.md
  src/content/operations/nat-traversal/_index.en.md
  src/static/images/natt/double_nat_scenario.svg
  src/static/images/natt/nat_scenario_all_private_routed.svg
  src/static/images/natt/nat_scenario_all_public.svg
  src/static/images/natt/nat_scenarios_1.svg
  src/static/images/natt/nat_scenarios_2.svg
  src/static/images/natt/public_private_selection_algorithm.svg
Labels: backport, documentation

#520 Add Project Owner responsibilities
  src/content/community/contributor-roles/_index.en.md
Labels: cncf, documentation, ready-to-test

#530 Update getting started deployment docs
  src/content/getting-started/_index.en.md
Labels: documentation

#532 Update community meeting information
  src/content/community/getting-help/_index.en.md
Labels: documentation

#534 Clarify branching phase of release process
  src/content/development/release-process/_index.en.md
Labels: documentation

#539 Collection of improvements for release docs
  src/content/development/release-process/_index.en.md
Labels: documentation

#537 OpenShift monitoring is now automatic
  src/content/operations/monitoring/_index.en.md
Labels: documentation

#547 Add linter to check no "Apply suggestions" commits
  .github/workflows/linting.yml
Labels: automation
