Repository submariner-io/submariner-website, pull requests merged in 2022-02, with the labels that each got.

#645 Update the automated release process description
  src/content/development/release-process/_index.en.md
Labels: documentation

#666 Add link to Istio with SubM blog post
  src/content/other-resources/_index.en.md
Labels: documentation

#667 Add Spotlight on SIG Multicluster link
  src/content/other-resources/_index.en.md
Labels: documentation

#672 Link to K8s Community DC talk about SubM
  src/content/other-resources/_index.en.md
Labels: documentation

#643 Add CI/CD maintenance docs, K8s version details
  src/content/development/_index.en.md
  src/content/development/building-testing/ci-maintenance/_index.en.md
Labels: documentation, blocked-on-rereview

#676 Add Help Wanted docs, GH tag query
  src/content/development/_index.en.md
Labels: documentation

#674 Refactor deployment summary for operator clarity
  src/content/operations/deployment/_index.en.md
Labels: documentation

#680 Rm direct operator deploy docs in Getting Started
  src/content/getting-started/_index.en.md
Labels: documentation

#681 Add Shipyard image software to CI maintenance docs
  src/content/development/building-testing/ci-maintenance/_index.en.md
Labels: documentation, automation

#682 Doc manual version updates in release process
  src/content/development/release-process/_index.en.md
Labels: documentation, automation
