Repository submariner-io/submariner-website, pull requests merged in 2022-05, with the labels that each got.

#746 Add Dependabot updates of GitHub Actions
  .github/dependabot.yml
Labels: maintenance

#759 Update GHA maintenance docs for Dependabot
  src/content/development/building-testing/ci-maintenance/_index.en.md
Labels: docs

#739 [Release Guide] Document Test Days
  src/content/development/contribution-guide/_index.en.md
Labels: confirmed, blocked-on-rereview

#764 Ignore SubM Tweet URLs that 404 in GHA infra
  .markdownlinkcheck.json
Labels: maintenance
