Repository submariner-io/submariner-website, pull requests merged in 2023-01, with the labels that each got.

#875 Document project resources section of contribution guide
  src/content/development/contribution-guide/_index.en.md
Labels: documentation

#881 Fix broken links, HTML tags not supported
  src/content/development/release-process/_index.en.md
  src/content/development/shipyard/targets/_index.en.md
Labels: bug

#882 Fix OpenShift on GCP Prerequisites
  src/resources/shared/openshift/setup_openshift_gcp.md
Labels: documentation, 0.15.0-testday

#883 Change frequency of dependabot gh-action check to monthly
  .github/dependabot.yml
Labels: maintenance
